"""Modelo de proveedoress

Revision ID: 754a5af97926
Revises: c744088e3703
Create Date: 2026-03-22 22:54:45.851218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754a5af97926'
down_revision: Union[str, Sequence[str], None] = 'c744088e3703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'providers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'providers', type_='unique')
    # ### end Alembic commands ###
